name: compile jotpad
on: workflow_dispatch
jobs:
  build-executable:
    runs-on: windows-latest
    steps:
            - name: clone git repo
              uses: actions/checkout@v4
            - name: setup python
              uses: actions/setup-python@v5
            - name: install all dependencies
              run: |
                  pip install pipreqs
                  pipreqs . --force
                  pip install -r requirements.txt
                  pip install pyinstaller
            - name: PyInstaller Action
              run: |
                  pyinstaller main.spec
            - name: NSIS Action
              uses: joncloud/makensis-action@v4.1
              with:
                script-file: install_script.nsi
              - name: 'Upload Artifact'
                uses: actions/upload-artifact@v4
                with:
                  name: installer_file
                  path: JotPadInstaller.exe
                  retention-days: 5