name: compile jotpad
on: workflow_dispatch
jobs:
  build-executable:
    runs-on: windows-latest
    steps:
            - name: clone git repo
              uses: actions/checkout@v4
            - name: setup python
              uses: actions/setup-python@v5
            - name: get all required dependencies
              uses: ryan-rozario/pipreqs-action@master
            - name: install dependencies
              run: pip install -r requirements.txt
            - name: PyInstaller Action
              uses: Martin005/pyinstaller-action@v1.2.0
              with:
                spec: 'main.spec'
                requirements: 'requirements.txt'